jobs:

  lint:
    name: Lint
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    include: cider-ci/task_defaults.yml
    tasks:
      lint:
        include: cider-ci/lint_task-component.yml

  build:
    name: Build
    depends_on: &LINT_DEP
      lint passed:
        type: job
        job_key: lint
        states: [passed]
    run_when: *LINT_DEP
    include: cider-ci/task_defaults.yml
    tasks:
      build:
        include: cider-ci/build_task-component.yml

  test:
    name: Test
    depends_on: &BUILD_DEP
      build passed:
        type: job
        job_key: build
        states: [passed]
    run_when: *BUILD_DEP
    include: cider-ci/task_defaults.yml
    tasks:
      build-and-test:
        include: cider-ci/build-and-test_task-component.yml
