jobs:
  build:
    name: 'Build & Test'
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }

    task_defaults: &TASK_DEFAULTS
      environment_variables:
        CI: 'true'
      git_options:
        submodules:
          include_match: ^.*$
      traits:
        g2016: true

    task:
      scripts:
        build:
          timeout: 10 minutes
          body: |
            npm ci
            npm run build
        prepare_test:
          start_when:
            built: { script_key: build, states: [ passed ] }
          timeout: 10 minutes
          body: |
            npm add ./test/
        test:
          start_when:
            prepared: { script_key: prepare_test, states: [ passed ] }
          timeout: 10 minutes
          body: |
            npm run test

  lint:
    name: 'Lint'
    run_when:
      any branch is pushed: { type: branch, include_match: ^.*$ }
    task_defaults: *TASK_DEFAULTS
    task:
      scripts:
        lint:
          timeout: 10 minutes
          body: 'npm ci && npm run ci:lint'

